In [12]:
#train categorical data
import time
import pandas as pd
from tqdm import tqdm 

a = time.time()
chunksize = 10000
total_rows = 1183747 # 总行数
b = pd.read_csv('/Users/maguoyi/Downloads/bosch-production-line-performance/train_categorical.csv.zip', 
                dtype='object', chunksize=chunksize)  # 读取数据

dfs = []

processed_rows = 0  # 已处理的行数

    
with tqdm(total=total_rows, desc='Processing Rows') as pbar:
    for chunk in b:

        chunk = chunk.apply(lambda x: x.str.lstrip('T'))
        
        dfs.append(chunk)

        processed_rows += len(chunk)
        #time.sleep(0.01)  # 模拟处理时间延迟
        pbar.update(len(chunk))  # 更新进度条已处理的行数
        pbar.set_postfix({'Processed': f'{processed_rows}/{total_rows} ({processed_rows * 100 / total_rows:.2f}%)'})# 更新进度条百分比信息

data = pd.concat(dfs)
data.to_csv('/Users/maguoyi/Downloads/bosch-production-line-performance/train_categorical_to_num.csv.zip', index=False)

Processing Rows: 100%|█| 1183747/1183747 [38:00<00:00, 519.14it/s, Processed=118

In [2]:
import pandas as pd
category = pd.read_csv('/Users/maguoyi/Downloads/bosch-production-line-performance/train_categorical_to_num.csv.zip', 
                       nrows=10000, low_memory=False)
category.head()

,Id,L0_S1_F25,L0_S1_F27,L0_S1_F29,L0_S1_F31,L0_S2_F33,L0_S2_F35,L0_S2_F37,L0_S2_F39,L0_S2_F41,...,L3_S49_F4225,L3_S49_F4227,L3_S49_F4229,L3_S49_F4230,L3_S49_F4232,L3_S49_F4234,L3_S49_F4235,L3_S49_F4237,L3_S49_F4239,L3_S49_F4240
0,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
#test categorical data
import time
import pandas as pd
from tqdm import tqdm 

a = time.time()
chunksize = 10000
total_rows = 1183748 # 总行数
b = pd.read_csv('/Users/maguoyi/Downloads/bosch-production-line-performance/test_categorical.csv.zip', 
                dtype='object', chunksize=chunksize)  # 读取数据

dfs = []

processed_rows = 0  # 已处理的行数

    
with tqdm(total=total_rows, desc='Processing Rows') as pbar:
    for chunk in b:

        chunk = chunk.apply(lambda x: x.str.lstrip('T'))
        
        dfs.append(chunk)

        processed_rows += len(chunk)
        #time.sleep(0.01)  # 模拟处理时间延迟
        pbar.update(len(chunk))  # 更新进度条已处理的行数
        pbar.set_postfix({'Processed': f'{processed_rows}/{total_rows} ({processed_rows * 100 / total_rows:.2f}%)'})# 更新进度条百分比信息

data = pd.concat(dfs)
data.to_csv('/Users/maguoyi/Downloads/bosch-production-line-performance/test_categorical_to_num.csv.zip', index=False)

Processing Rows: 100%|█| 1183748/1183748 [15:25<00:00, 1279.11it/s, Processed=11

In [4]:
category_test = pd.read_csv('/Users/maguoyi/Downloads/bosch-production-line-performance/test_categorical_to_num.csv.zip', 
                       nrows=10000, low_memory=False)
category_test.head()

,Id,L0_S1_F25,L0_S1_F27,L0_S1_F29,L0_S1_F31,L0_S2_F33,L0_S2_F35,L0_S2_F37,L0_S2_F39,L0_S2_F41,...,L3_S49_F4225,L3_S49_F4227,L3_S49_F4229,L3_S49_F4230,L3_S49_F4232,L3_S49_F4234,L3_S49_F4235,L3_S49_F4237,L3_S49_F4239,L3_S49_F4240
0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN